-- Administración: roles separados de planes y auditoría ligera.
-- Ejecuta una vez en Supabase > SQL Editor, después de pro-fridge-schema.sql.

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists role text not null default 'user';

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user', 'admin'));

update public.profiles p
set email = u.email,
    display_name = coalesce(
      nullif(u.raw_user_meta_data ->> 'full_name', ''),
      nullif(u.raw_user_meta_data ->> 'name', ''),
      p.display_name
    )
from auth.users u
where p.id = u.id and (p.email is distinct from u.email or p.display_name is null);

update public.profiles set role = 'user' where role is null;

create or replace function public.create_user_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), nullif(new.raw_user_meta_data ->> 'name', ''))
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = coalesce(excluded.display_name, profiles.display_name),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists create_user_profile_after_signup on auth.users;
create trigger create_user_profile_after_signup
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.create_user_profile();

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('plan_changed')),
  old_value text,
  new_value text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_admin_created_idx
on public.admin_audit_logs(admin_user_id, created_at desc);

alter table public.admin_audit_logs enable row level security;

-- No policies de escritura: el navegador no puede crear ni modificar auditorías.
-- Las operaciones administrativas se realizan exclusivamente desde el servidor.
revoke all on public.admin_audit_logs from anon, authenticated;
revoke insert, update, delete on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;

-- Convierte manualmente la primera cuenta en administrador:
-- update public.profiles
-- set role = 'admin', plan = 'pro', pro_expires_at = null, updated_at = now()
-- where id = 'UUID_DEL_USUARIO';
