"use client";
import { Share, SquarePlus, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useI18n } from "@/lib/i18n";
const KEY = "pwa-install-guide-dismissed";
type IosNavigator = Navigator & { standalone?: boolean };
const eligible = () => (/iPad|iPhone|iPod/.test(navigator.userAgent) || (navigator.platform === "MacIntel" && navigator.maxTouchPoints > 1)) && /Safari/.test(navigator.userAgent) && !/CriOS|FxiOS|EdgiOS|OPiOS/.test(navigator.userAgent) && !window.matchMedia("(display-mode: standalone)").matches && (navigator as IosNavigator).standalone !== true;
export function IosPwaInstallGuide() {
  const { t } = useI18n();
  const [open, setOpen] = useState(false);
  useEffect(() => { let dismissed = false; try { dismissed = localStorage.getItem(KEY) === "true"; } catch {} if (!eligible() || dismissed) return; const timer = window.setTimeout(() => setOpen(true), 750); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!open) return; const escape = (event: KeyboardEvent) => event.key === "Escape" && setOpen(false); window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [open]);
  if (!open) return null;
  const steps = [{ icon: <Share size={21}/>, title: t("pwa.stepShare"), text: t("pwa.stepShareHint") }, { icon: <SquarePlus size={21}/>, title: t("pwa.stepAdd"), text: t("pwa.stepAddHint") }];
  const neverShow = () => { try { localStorage.setItem(KEY, "true"); } catch {} setOpen(false); };
  return <div className="ios-install-guide fixed inset-0 z-[100] flex items-end bg-black/45" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="ios-install-title" aria-describedby="ios-install-description" className="ios-install-sheet sheet relative mx-auto max-h-[88dvh] w-full max-w-lg overflow-y-auto rounded-t-[30px] bg-white px-5 pb-[max(1rem,env(safe-area-inset-bottom))] pt-4 shadow-2xl"><div className="mx-auto mb-3 h-1.5 w-10 rounded-full bg-black/10" aria-hidden="true"/><button onClick={() => setOpen(false)} aria-label={t("pwa.close")} className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-full bg-[#f1f4f2] text-[#53655c]"><X size={20}/></button><div className="px-8 text-center"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#176b46]">Gasto Listo</p><h2 id="ios-install-title" className="mt-1 text-2xl font-bold tracking-[-.02em]">{t("pwa.title")}</h2><p id="ios-install-description" className="mt-1.5 text-sm text-[#587067]">{t("pwa.description")}</p></div><div className="mt-4 space-y-2.5">{steps.map((step) => <div key={step.title} className="ios-install-step flex gap-3 rounded-2xl bg-[#f3f6f3] p-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e5f3ea] text-[#176b46]">{step.icon}</span><span className="min-w-0"><b className="block text-sm">{step.title}</b><small className="mt-0.5 block leading-relaxed text-[#718078]">{step.text}</small></span></div>)}</div><p className="mt-3 text-center text-xs leading-relaxed text-[#718078]">{t("pwa.result")}</p><button onClick={() => setOpen(false)} className="mt-4 min-h-14 w-full rounded-2xl bg-[#176b46] px-4 font-bold text-white">{t("pwa.understood")}</button><button onClick={neverShow} className="min-h-12 w-full px-4 text-sm font-bold text-[#176b46]">{t("pwa.neverShow")}</button></section></div>;
}
